-- NOTE: This file is auto generated by ./sql-generator

-- PersonDetailRepository.getForPerson
select
  "id",
  "parentId",
  "key",
  "value",
  "sortOrder",
  "createdAt"
from
  "person_detail"
where
  "personId" = $1
order by
  "sortOrder",
  "createdAt"

-- PersonDetailRepository.getAlongWith
with
  "matched" as (
    select
      lower(detail."key") as "key",
      lower(detail."value") as "value",
      "detail"."id" as "detailId",
      "person"."id" as "personId",
      "person"."name" as "name"
    from
      "person_detail" as "detail"
      inner join "person" on "person"."id" = "detail"."personId"
    where
      "detail"."ownerId" = $1
      and "detail"."personId" != $2
      and "detail"."parentId" is null
      and (lower(detail."key"), lower(detail."value")) in (
        select
          lower("key"),
          lower("value")
        from
          "person_detail"
        where
          "personId" = $3
          and "parentId" is null
      )
  ),
  "subject" as (
    select
      lower(parent."key") as "key",
      lower(parent."value") as "value",
      lower(sub."key") as "subKey",
      lower(sub."value") as "subValue"
    from
      "person_detail" as "parent"
      inner join "person_detail" as "sub" on "sub"."parentId" = "parent"."id"
    where
      "parent"."personId" = $4
      and "parent"."parentId" is null
  ),
  "overlap" as (
    select distinct
      "matched"."detailId" as "detailId",
      "subject"."subKey" as "subKey",
      "subject"."subValue" as "subValue"
    from
      "matched"
      inner join "person_detail" as "sub" on "sub"."parentId" = "matched"."detailId"
      inner join "subject" on "subject"."key" = "matched"."key"
      and "subject"."value" = "matched"."value"
      and "subject"."subKey" = lower(sub."key")
      and "subject"."subValue" = lower(sub."value")
  ),
  "overlapCounts" as (
    select
      "detailId",
      count(*) as "subShared",
      array_agg("subKey") as "subKeys",
      array_agg("subValue") as "subValues"
    from
      "overlap"
    group by
      "detailId"
  ),
  "best" as (
    select distinct
      on (
        "matched"."key",
        "matched"."value",
        "matched"."personId"
      ) "matched"."key" as "key",
      "matched"."value" as "value",
      "matched"."personId" as "personId",
      "matched"."name" as "name",
      coalesce("overlapCounts"."subShared", 0) as "subShared",
      coalesce("overlapCounts"."subKeys", '{}') as "subKeys",
      coalesce("overlapCounts"."subValues", '{}') as "subValues"
    from
      "matched"
      left join "overlapCounts" on "overlapCounts"."detailId" = "matched"."detailId"
    order by
      "matched"."key",
      "matched"."value",
      "matched"."personId",
      coalesce("overlapCounts"."subShared", 0) desc
  ),
  "scored" as (
    select
      *,
      count(*) over (
        partition by
          "personId"
      ) as "shared",
      array_agg("key") over (
        partition by
          "personId"
      ) as "matchedKeys"
    from
      "best"
  ),
  "ranked" as (
    select
      *,
      row_number() over (
        partition by
          "key",
          "value"
        order by
          "subShared" desc,
          "shared" desc,
          "name",
          "personId"
      ) as "rank",
      count(*) over (
        partition by
          "key",
          "value"
      ) as "total"
    from
      "scored"
  )
select
  *
from
  "ranked"
where
  "rank" <= $5
order by
  "key",
  "value",
  "rank"

-- PersonDetailRepository.getKeySuggestions
with
  "counts" as (
    select
      "detail"."key" as "key",
      count(*) as "count"
    from
      "person_detail" as "detail"
    where
      "detail"."ownerId" = $1
      and "detail"."parentId" is null
      and "detail"."key" ilike $2
    group by
      "detail"."key"
  ),
  "ranked" as (
    select
      "key",
      sum("count") over (
        partition by
          lower("key")
      ) as "total",
      row_number() over (
        partition by
          lower("key")
        order by
          "count" desc,
          "key"
      ) as "rank"
    from
      "counts"
  )
select
  "key" as "value",
  "total"
from
  "ranked"
where
  "rank" = $3
order by
  "total" desc,
  "value"
limit
  $4

-- PersonDetailRepository.getValueSuggestions
with
  "counts" as (
    select
      "detail"."value" as "value",
      count(*) as "count"
    from
      "person_detail" as "detail"
    where
      "detail"."ownerId" = $1
      and lower(detail."key") = $2
      and "detail"."parentId" is null
      and "detail"."value" ilike $3
    group by
      "detail"."value"
  ),
  "ranked" as (
    select
      "value",
      sum("count") over (
        partition by
          lower("value")
      ) as "total",
      row_number() over (
        partition by
          lower("value")
        order by
          "count" desc,
          "value"
      ) as "rank"
    from
      "counts"
  )
select
  "value",
  "total"
from
  "ranked"
where
  "rank" = $4
order by
  "total" desc,
  "value"
limit
  $5

-- PersonDetailRepository.getConflicts
select distinct
  on (lower(detail."key"), "detail"."personId") lower(detail."key") as "key",
  "person"."id" as "personId",
  "person"."name" as "name",
  "detail"."id" as "detailId",
  "detail"."value" as "value"
from
  "person_detail" as "detail"
  inner join "person" on "person"."id" = "detail"."personId"
where
  "detail"."ownerId" = $1
  and "detail"."personId" in ($2)
  and "detail"."parentId" is null
  and lower(detail."key") in ($3)
order by
  lower(detail."key"),
  "detail"."personId",
  "detail"."sortOrder",
  "detail"."createdAt"
